In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [ ]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0  colegio-bachilleres.com.mx        0        0           0          0   
1                 twitter.com        0        0           1          1   
2              thenextweb.com        0        0           1          6   
3               pitchfork.com        0        0           1          3   
4     greenworldlogistics.com        0        0           0          1   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              1           0            1   
1            0             0        0              0           0            1   
2            0             0        0              0           0            1   
3            0             0        0              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           0           1       0           0            1             0   
1           1           1       0           0            1             0   
2           0           0       0           0            1             0   
3           1           1       0           0            1             0   
4           0           1       0           0            1             0   

   Label  
0      1  
1      0  
2      0  
3      0  
4      1

In [ ]:
X = data.drop(['Domain', 'Label'], axis=1)

In [ ]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           0          0            0             0   
1        0        0           1          1            0             0   
2        0        0           1          6            0             0   
3        0        0           1          3            0             0   
4        0        0           0          1            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              1           0            1           0           1   
1        0              0           0            1           1           1   
2        0              0           0            1           0           0   
3        0              0           0            1           1           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [ ]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [ ]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8013333333333333
Precision: 0.82295909261947
Recall: 0.8013333333333333
F1 Score: 0.7975896654476501
Confusion Matrix:
[[1414  102]
 [ 494  990]]

SVC Metrics:
Accuracy: 0.8396666666666667
Precision: 0.8695949382099359
Recall: 0.8396666666666667
F1 Score: 0.8360582412012971
Confusion Matrix:
[[1490   26]
 [ 455 1029]]

RandomForestClassifier Metrics:
Accuracy: 0.8566666666666667
Precision: 0.8626765881078151
Recall: 0.8566666666666667
F1 Score: 0.855950834240797
Confusion Matrix:
[[1399  117]
 [ 313 1171]]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.8573333333333333
Precision: 0.8741132747868144
Recall: 0.8573333333333333
F1 Score: 0.8555228556939147
Confusion Matrix:
[[1462   54]
 [ 374 1110]]

KNeighborsClassifier Metrics:
Accuracy: 0.8513333333333334
Precision: 0.858986923539392
Recall: 0.8513333333333334
F1 Score: 0.850395161881177
Confusion Matrix:
[[1404  112]
 [ 334 1150]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8546666666666667
Precision: 0.8605133142934855
Recall: 0.8546666666666667
F1 Score: 0.8539546263513542
Confusion Matrix:
[[1395  121]
 [ 315 1169]]


In [ ]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
3           MLPClassifier  0.857333   0.874113  0.857333  0.855523
2  RandomForestClassifier  0.856667   0.862677  0.856667  0.855951
5  DecisionTreeClassifier  0.854667   0.860513  0.854667  0.853955
4    KNeighborsClassifier  0.851333   0.858987  0.851333  0.850395
1                     SVC  0.839667   0.869595  0.839667  0.836058
0      LogisticRegression  0.801333   0.822959  0.801333  0.797590
